with raw_source as (

    select *
    from {{ source('raw', 'facilities') }}

)

   , final as (select
    "WorkOrderNo"::                varchar as workorderno ,
    "Name"::                       varchar as name ,
    "ParentWorkOrderId"::          varchar as parentworkorderid ,
    "ParentWorkOrderNo"::          varchar as parentworkorderno ,
    "WOStatusId"::                 varchar as wostatusid ,
    "WOStatusNo"::                 varchar as wostatusno ,
    "WOStatusName"::               varchar as wostatusname ,
    "PriorityId"::                 varchar as priorityid ,
    "PriorityNo"::                 varchar as priorityno ,
    "PriorityName"::               varchar as priorityname ,
    "WorkCategoryId"::             varchar as workcategoryid ,
    "WorkCategoryNo"::             varchar as workcategoryno ,
    "WorkCategoryName"::           varchar as workcategoryname ,
    "WorkTypeId"::                 varchar as worktypeid ,
    "WorkTypeNo"::                 varchar as worktypeno ,
    "WorkTypeName"::               varchar as worktypename ,
    "SourceType"::                 varchar as sourcetype ,
    "ProblemId"::                  varchar as problemid ,
    "ProblemNo"::                  varchar as problemno ,
    "ProblemName"::                varchar as problemname ,
    "CauseId"::                    varchar as causeid ,
    "CauseNo"::                    varchar as causeno ,
    "CauseName"::                  varchar as causename ,
    "CostCenterId"::               varchar as costcenterid ,
    "CostCenterNo"::               varchar as costcenterno ,
    "CostCenterName"::             varchar as costcentername ,
    "ProjectId"::                  varchar as projectid ,
    "ProjectNo"::                  varchar as projectno ,
    "ProjectName"::                varchar as projectname ,
    "OriginType"::                 varchar as origintype ,
    "OriginatorId"::               varchar as originatorid ,
    "OriginatorUserNo"::           varchar as originatoruserno ,
    "OriginatorUserFirstName"::    varchar as originatoruserfirstname ,
    "OriginatorUserLastName"::     varchar as originatoruserlastname ,
    "OriginatorPMNo"::             varchar as originatorpmno ,
    "OriginatorPMName"::           varchar as originatorpmname ,
    "DateOriginated"::             varchar as dateoriginated ,
    "DateExpected"::               varchar as dateexpected ,
    "DateAssigned"::               varchar as dateassigned ,
    "DateCompleted"::              varchar as datecompleted ,
    "DateUpdated"::                varchar as dateupdated ,
    "LaborHours"::                 varchar as laborhours ,
    "LaborCost"::                  varchar as laborcost ,
    "PartCost"::                   varchar as partcost ,
    "OtherHours"::                 varchar as otherhours ,
    "OtherCost"::                  varchar as othercost ,
    "PartNonInventoryCost"::       varchar as partnoninventorycost ,
    "EstimatedHours"::             varchar as estimatedhours ,
    "EstimatedCost"::              varchar as estimatedcost ,
    "Downtime"::                   varchar as downtime ,
    "WorkRequested"::              varchar as workrequested ,
    "RequesterAvailabilityNotes":: varchar as requesteravailabilitynotes ,
    "Action"::                     varchar as action ,
    "Comment"::                    varchar as comment ,
    "LastSignedOn"::               varchar as lastsignedon ,
    "LastSignedBy"::               varchar as lastsignedby ,
    "WorkOrderCreationReading"::   varchar as workordercreationreading ,
    "WorkOrderTriggerDate"::       varchar as workordertriggerdate ,
    "WorkOrderTriggerMeterTitle":: varchar as workordertriggermetertitle ,
    "WorkOrderTriggerAsset"::      varchar as workordertriggerasset ,
    "SourceEstimatedHours_1"::     varchar as sourceestimatedhours_1 ,
    "SiteId_1"::                   varchar as siteid_1 ,
    "SiteNo_1"::                   varchar as siteno_1 ,
    "SiteName_1"::                 varchar as sitename_1 ,
    "LocationId_1"::               varchar as locationid_1 ,
    "LocationNo_1"::               varchar as locationno_1 ,
    "LocationSiteName_1"::         varchar as locationsitename_1 ,
    "LocationName_1"::             varchar as locationname_1 ,
    "AssetId_1"::                  varchar as assetid_1 ,
    "AssetNo_1"::                  varchar as assetno_1 ,
    "AssetSiteName_1"::            varchar as assetsitename_1 ,
    "AssetName_1"::                varchar as assetname_1 ,
    "MeterTitleId_1"::             varchar as metertitleid_1 ,
    "MeterTitleNo_1"::             varchar as metertitleno_1 ,
    "MeterTitleName_1"::           varchar as metertitlename_1 ,
     "test_col"                     ::integer as test_col

from raw_source

    )

select * from final