with raw_source as (

    select *
    from {{ source('raw', 'facilities') }}

)

   , final as (select
    "WorkOrderNo"::                varchar as work_order_no ,
    "Name"::                       varchar as name ,
    "ParentWorkOrderId"::          varchar as parent_work_order_id ,
    "ParentWorkOrderNo"::          varchar as parent_work_order_no ,
    "WOStatusId"::                 varchar as wo_status_id ,
    "WOStatusNo"::                 varchar as wo_status_no ,
    "WOStatusName"::               varchar as wo_status_name ,
    "PriorityId"::                 varchar as priority_id ,
    "PriorityNo"::                 varchar as priority_no ,
    "PriorityName"::               varchar as priority_name ,
    "WorkCategoryId"::             varchar as work_category_id ,
    "WorkCategoryNo"::             varchar as work_category_no ,
    "WorkCategoryName"::           varchar as work_category_name ,
    "WorkTypeId"::                 varchar as work_type_id ,
    "WorkTypeNo"::                 varchar as work_type_no ,
    "WorkTypeName"::               varchar as work_type_name ,
    "SourceType"::                 varchar as source_type ,
    "ProblemId"::                  varchar as problem_id ,
    "ProblemNo"::                  varchar as problem_no ,
    "ProblemName"::                varchar as problem_name ,
    "CauseId"::                    varchar as cause_id ,
    "CauseNo"::                    varchar as cause_no ,
    "CauseName"::                  varchar as cause_name ,
    "CostCenterId"::               varchar as cost_center_id ,
    "CostCenterNo"::               varchar as cost_center_no ,
    "CostCenterName"::             varchar as cost_center_name ,
    "ProjectId"::                  varchar as project_id ,
    "ProjectNo"::                  varchar as project_no ,
    "ProjectName"::                varchar as project_name ,
    "OriginType"::                 varchar as origin_type ,
    "OriginatorId"::               varchar as originator_id ,
    "OriginatorUserNo"::           varchar as originator_user_no ,
    "OriginatorUserFirstName"::    varchar as originator_user_first_name ,
    "OriginatorUserLastName"::     varchar as originator_user_last_name ,
    "OriginatorPMNo"::             varchar as originator_pm_no ,
    "OriginatorPMName"::           varchar as originator_pm_name ,
    "DateOriginated"::             varchar as date_originated ,
    "DateExpected"::               varchar as date_expected ,
    "DateAssigned"::               varchar as date_assigned ,
    "DateCompleted"::              varchar as date_completed ,
    "DateUpdated"::                varchar as date_updated ,
    "LaborHours"::                 varchar as labor_hours ,
    "LaborCost"::                  varchar as labor_cost ,
    "PartCost"::                   varchar as part_cost ,
    "OtherHours"::                 varchar as other_hours ,
    "OtherCost"::                  varchar as other_cost ,
    "PartNonInventoryCost"::       varchar as part_non_inventory_cost ,
    "EstimatedHours"::             varchar as estimated_hours ,
    "EstimatedCost"::              varchar as estimated_cost ,
    "Downtime"::                   varchar as down_time ,
    "WorkRequested"::              varchar as work_requested ,
    "RequesterAvailabilityNotes":: varchar as requester_availability_notes ,
    "Action"::                     varchar as action_taken ,
    "Comment"::                    varchar as comment ,
    "LastSignedOn"::               varchar as last_signed_on ,
    "LastSignedBy"::               varchar as last_signed_by ,
    "WorkOrderCreationReading"::   varchar as work_order_creation_reading ,
    "WorkOrderTriggerDate"::       varchar as work_order_trigger_date ,
    "WorkOrderTriggerMeterTitle":: varchar as work_order_trigger_meter_title ,
    "WorkOrderTriggerAsset"::      varchar as work_order_trigger_asset ,
    "SourceEstimatedHours_1"::     varchar as source_estimated_hours_1 ,
    "SiteId_1"::                   varchar as site_id_1 ,
    "SiteNo_1"::                   varchar as site_no_1 ,
    "SiteName_1"::                 varchar as site_name_1 ,
    "LocationId_1"::               varchar as location_id_1 ,
    "LocationNo_1"::               varchar as location_no_1 ,
    "LocationSiteName_1"::         varchar as location_site_name_1 ,
    "LocationName_1"::             varchar as location_name_1 ,
    "AssetId_1"::                  varchar as asset_id_1 ,
    "AssetNo_1"::                  varchar as asset_no_1 ,
    "AssetSiteName_1"::            varchar as asset_site_name_1 ,
    "AssetName_1"::                varchar as asset_name_1 ,
    "MeterTitleId_1"::             varchar as meter_title_id_1 ,
    "MeterTitleNo_1"::             varchar as meter_title_no_1 ,
    "MeterTitleName_1"::           varchar as meter_title_name_1 ,
     "test_col"                     ::integer as test_col

from raw_source

    )

select * from final