transform:
  target: dev_postgres
  outputs:
    dev:
      type: duckdb
      path: '/Users/Alexander.Vasquez-Jaffe/Code/swarthmore-facilities-data/transform/facilitiesfulltestdatabase_1_29.db'
      schema: main

    dev_postgres:
      type: postgres
      host: localhost
      user: alex
      password: secret123
      port: 5432
      dbname: analytics
      schema: dbt_alex
      threads: 4
